
#server:
#  port: 8090

#spring.datasource.url: jdbc:mysql://localhost:8090/db
#spring.datasource.username:
#spring.datasource.password:
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.database-platform : org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl: true
#spring.jpa.hibernate.ddl-auto : update

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true

spring :
  datasource:
    url : jdbc:postgresql://ec2-52-30-159-47.eu-west-1.compute.amazonaws.com:5432/d9migjrb58ir61
    username: xnxrguoehbsltg
    password: 4f082cba5930fc4dd57675b1bf5051be3fde8d1c421c0060e1858480b796526a
  jpa:
    hibernate:
      ddl-auto: update

#  mail:
#     host: smtp.gmail.com
#     port: 587
#     username:
#     password:
#     properties.mail.smtp.auth: true
#     properties.mail.smtp.starttls.enable: true
